{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:
let
  stylixQt5ctConf = ''
    [Appearance]
    icon_theme=Papirus
    style=kvantum
    [Fonts]
    fixed="JetBrainsMono Nerd Font,11"
    general="Noto Sans,11"
  '';

  localGeminiTextTools = inputs.vicinae.lib.${pkgs.stdenv.hostPlatform.system}.mkVicinaeExtension {
    pname = "vicinae-extension-gemini-text-tools";
    version = "0";
    src = ./vicinae/extensions/gemini-text-tools;
  };

  stylixColors = config.lib.stylix.colors.withHashtag;
in
{
  programs.vicinae = {
    enable = true;

    # Use the module's systemd integration
    systemd.enable = true;

    settings = {
      launcher_window = {
        opacity = 1.0;
        client_side_decorations = {
          enabled = true;
        };
        layer_shell = {
          enabled = false; # Disabled for niri compatibility
        };
      };
      theme = {
        light = {
          name = "stylix";
          icon_theme = "Papirus";
        };
        dark = {
          name = "stylix";
          icon_theme = "Papirus";
        };
      };
    };

    extensions = with inputs.vicinae-extensions.packages.${pkgs.stdenv.hostPlatform.system}; [
      # bluetooth # TODO: re-enable once usocket builds with Node.js 24
      localGeminiTextTools
      nix
      wifi-commander
    ];

    themes.stylix = {
      meta = {
        name = "stylix";
        description = "theme generated by stylix";
        variant = if config.stylix.polarity == "either" then "light" else config.stylix.polarity;
      };
      colors = with stylixColors; {
        core = {
          background = base00;
          foreground = base05;
          secondary_background = base01;
          border = base02;
          accent = base0D;
        };
        accents = {
          blue = base0D;
          green = base0B;
          magenta = base0E;
          orange = base09;
          purple = base0E;
          red = base08;
          yellow = base0A;
          cyan = base0C;
        };
        list.item = {
          selection = {
            background = base02;
            secondary_background = base03;
          };
          hover.background = base01;
        };
      };
    };
  };

  # Avoid Stylix's built-in Vicinae target until it stops writing renamed
  # services.vicinae aliases; keep the equivalent theme config above.
  stylix.targets.vicinae.enable = false;

  # GTK icon theme (which Qt/vicinae will respect)
  gtk = {
    # Keep GTK4 on libadwaita; override Stylix's generated GTK4 theme.
    gtk4.theme = lib.mkForce null;
    iconTheme = {
      package = pkgs.papirus-icon-theme;
      name = "Papirus";
    };
  };

  # Override Stylix's Qt config to add icon theme
  stylix.targets.qt.enable = lib.mkForce false;

  home.file.".config/qt5ct/qt5ct.conf".text = stylixQt5ctConf;
  home.file.".config/qt6ct/qt6ct.conf".text = stylixQt5ctConf;
}
